### PR TITLE
fix navbar going white

### PR DESCRIPTION
**Pull request by Phavion**

### CODE REVIEW

**Comment by emielvanrijn** [comment]
Alrighty, LGTM! For another time: we should style the navbar by adjusting the theme :)...

**Comment by cdfa** [comment]
> For another time: we should style the navbar by adjusting the theme :)...

I think I tried that and it didn't work :(. Not 100% sure I did it right though.

**Comment by emielvanrijn** [comment]
Did you try adding the `primary` prop to the navbar? I already changed the default value of `primary`

**Comment by cdfa** [comment]
No not yet, I don't think it's a valid prop for `semantic-ui`'s `<Menu>` either, but you could try.

**Pull request merged**
