### PR TITLE
Development

### PR DESCRIPTION
**Pull request by emielvanrijn**

### CODE REVIEW

**Comment by emielvanrijn** [comment]
@cdfa I can not reproduce, not even with fresh install, neither can netlify it seems. Have you installed the latest version of gatsby-cli, which now is v2 instead of the specific version in the README? Will update the readme though...

**Comment by cdfa** [comment]
Did a fresh install and now i'm getting this:
```
These dependencies were not found:

* @babel/runtime/helpers/builtin/interopRequireDefault in ./~/@material-ui/core/index.js, ./~/@material-ui/core/styles/index.js and 245 others
* @babel/runtime/helpers/builtin/interopRequireWildcard in ./~/@material-ui/core/index.js, ./~/@material-ui/core/styles/MuiThemeProvider.js and 4 others
* @babel/runtime/helpers/builtin/objectSpread in ./~/@material-ui/core/styles/createMuiTheme.js, ./~/@material-ui/core/styles/MuiThemeProvider.js and 39 others
* @babel/runtime/helpers/builtin/objectWithoutProperties in ./~/@material-ui/core/styles/createMuiTheme.js, ./~/@material-ui/core/styles/withStyles.js and 109 others
* @babel/runtime/helpers/builtin/defineProperty in ./~/@material-ui/core/styles/MuiThemeProvider.js, ./~/@material-ui/core/styles/createMixins.js and 65 others
* @babel/runtime/helpers/builtin/classCallCheck in ./~/@material-ui/core/styles/MuiThemeProvider.js, ./~/@material-ui/core/styles/withStyles.js and 46 others
* @babel/runtime/helpers/builtin/createClass in ./~/@material-ui/core/styles/MuiThemeProvider.js, ./~/@material-ui/core/styles/withStyles.js and 46 others
* @babel/runtime/helpers/builtin/possibleConstructorReturn in ./~/@material-ui/core/styles/MuiThemeProvider.js, ./~/@material-ui/core/styles/withStyles.js and 45 others
* @babel/runtime/helpers/builtin/inherits in ./~/@material-ui/core/styles/MuiThemeProvider.js, ./~/@material-ui/core/styles/withStyles.js and 45 others
* @babel/runtime/helpers/builtin/extends in ./~/@material-ui/core/styles/withStyles.js, ./~/@material-ui/core/styles/withTheme.js and 99 others
* @babel/runtime/helpers/builtin/assertThisInitialized in ./~/@material-ui/core/ButtonBase/ButtonBase.js, ./~/@material-ui/core/ClickAwayListener/ClickAwayListener.js and 3 others
* @babel/runtime/helpers/builtin/toConsumableArray in ./~/@material-ui/core/GridListTile/GridListTile.js, ./~/@material-ui/core/MobileStepper/MobileStepper.js and 2 others
* @babel/runtime/helpers/builtin/typeof in ./~/@material-ui/core/utils/helpers.js, ./~/@material-ui/core/~/react-event-listener/dist/react-event-listener.cjs.js
```

**Comment by emielvanrijn** [comment]
@cdfa those dependencies are completely inexistend with this PR, I actually removed all references. Are you on the right branch?

**Comment by cdfa** [comment]
Reinstalled on WSL and it worked. Really weird...

**Pull request merged**
