### PR TITLE
Fix #187

### LINKED ISSUE #187: Mobile navbar isn't up to date with translations
All the URLs in the navbar link to their normal pages without the current language identifier. The language switch is also using an older version, so it replaces the .nl instead of the /nl.

### PR DESCRIPTION
**Pull request by Mstiekema**

### CODE REVIEW

**Comment by Mstiekema** [comment]
Will fix the nav part of it tomorrow

**Comment by Mstiekema** [comment]
Please test the deploy preview and beta site thoroughly before merging this PR. If you find any untranslated strings or weird behavior, please let me know.

This PR does still contain some dutch hardcoded strings. These will be fixed in future issues
- Menu.json should be transfered to contentful #185 
- Footer needs a refactor #137

**Comment by Riscky** [comment]
looking good, few remarks:
- there should be a space between 'companymailing' (en-us.json, mailchimp.company)
- Back-buttons on committee pages are untranslated
- Back-buttons on society pages link back to the wrong language or show a blank page
- Studie (in the navbar) is untranslated

**Comment by Mstiekema** [comment]
I fixed the issues you mentioned. Some could not be fixed because of the following:

>     * Back-buttons on committee pages are untranslated
These were already translated on this branch.

>     * Studie (in the navbar) is untranslated
This is something which should be translated from contentful

**Pull request merged**
