### PR TITLE
commented the intro information so it can be reused next year

### PR DESCRIPTION
**Pull request by sam32123**
Comment out the important introduction related components, so they can be reused next year, but are not used currently.

It ain't pretty, but it works :)

### CODE REVIEW

**Comment by TobiasDeBruijn** [comment]
Could we do this via contentful perhaps?

**Comment by stickyPiston** [comment]
It favour doing to it via contentful too, or let it be done automatically based on the date in the year

**Comment by sam32123** [comment]
> It favour doing to it via contentful too, or let it be done automatically based on the date in the year

let's look at it in 2 hours!

**Comment by SilasPeters** [comment]
Then I would be highly in favor of making this depend on contentfull I suggest we rename this PR and do that instead

**Comment by stickyPiston** [comment]
unpublishing the intro information currently results in a build error, so i've added a fix so that unpublishing just ignores the intro information and patches the rest of the home page layout. Love to have a quick review on this from someone else, so we can merge this.

**Review by SilasPeters — APPROVED** [review]

**Comment by stickyPiston** [comment]
Yes, we totally can ^_^

**Pull request merged**
